replicaCount: 1

image:
  repository: prom/prometheus
  tag: "v2.50.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

resources: {}

scrapeConfigs:
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: node-exporter
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        regex: "true"
        action: keep
